### ISSUE TITLE
I18N - translated labels and values in the DialogBoxItems

### ISSUE THREAD

**Issue by mike4git** [teamneusta/pimcore-areabrick-config-bundle#10]
The labels of the tabs or the input/select/checkbox items should be internationalized.

Ideally one will create them by given admin translation keys and translation will be done by Pimcore I18N feature (TranslationService)

**Comment by robin-ntriga** [comment]
This is possible using the Symfony TranslatorInterface:
`
...
use Symfony\Contracts\Translation\TranslatorInterface

private $translator;

public function __construct(TranslatorInterface $translator) {
       $this->translator = $translator;
}
...
`

And inside the buildDialogBox function:

`$this->translator->trans('My translation', [], 'admin')`

**Comment by m0nken** [comment]
@robin-ntriga I tried that and your solution works perfectly fine for me. Actually I used `Pimcore\Translation\Translator` and that worked as well.

**Comment by jdreesen** [comment]
Here is a PR that adds native support for translations: #43
